apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: creeper-api-ingress
  namespace: creeper
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      real_ip_header CF-Connecting-IP;
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - api.creeper.banano.cc
      secretName: api-creeper-banano-cc-v6-server-secret
  rules:
    - host: api.creeper.banano.cc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: creeper-api-service
                port:
                  number: 3001
