name: CI

on:
  push:
    branches:
      - master

jobs:
  build_server:
    name: Build Server
    runs-on: ubuntu-latest
    env:
      GITHUB_RUN_ID: ${{ github.run_id }}
    steps:
      - uses: actions/checkout@master

      - name: Build and tag
        shell: bash
        run: cd server && yarn && yarn build
